jwt.secret : javainuse
server.port : 8888
spring:
  cloud:
    config:
      server:
        git:
          uri : https://github.com/thetechnojournals/microservices
          searchPaths: App-Configurations
          username: ${git_user}
          password: ${git_password}
          force-pull: true

    bus:
      enabled: true
#      destination: TTJ_APP_CONFIG
  rabbitmq:
    host: rabbitmq.local
    port: 5672
    virtual-host: /
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/login
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

spring.security.user.name: config_user
spring.security.user.password: config_user

management:
  endpoints:
    web:
      exposure:
        include: '*'
